spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event-manager
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/event-manager
    user: postgres
    password: postgres
    locations: classpath:db/migration/migration-postgres
