spring:
  datasource:
    url: ${URL}:${PORT}/${DATABASE}
    username: ${CLOUD_USER}
    password: ${PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: ${SCHEMA}
        format_sql: true
  flyway:
    url: ${URL}:${PORT}/${DATABASE}
    user: ${CLOUD_USER}
    password: ${PASSWORD}
    locations: classpath:db/migration/migration-postgres
    schemas: ${SCHEMA}
  h2:
    console:
      enabled: false